### ISSUE TITLE
Pypi version is broken

### ISSUE THREAD

**Issue by vandersonmota** [davidcrawford/chronic#1]
hi, i got this error when using pypi's version.

``` python
import chronic

@chronic.time
def spam():
    #stuff

chronic.py", line 39, in <module>
    from proxy import Proxy
ImportError: No module named proxy
```

This error does not happens when i use the repository version.

Thanks!

**Comment by davidcrawford** [comment]
Thanks!  I'll look into it now.

**Comment by davidcrawford** [comment]
Okay, I think I just needed to add proxy to setup.py.  That's pushed now.
 Thanks for the report.
